version: '2'

networks:
  net1:
    driver: bridge

services:
  postgresql:
    image: 'postgres:latest'
    networks:
      - net1
    ports:
      - '5432:5432'
  rstudio-image:
    image: 'amanskywalker/rstudio-image'
    networks:
      - net1
    ports:
      - '8787:8787'
